export const tranMap = {
  AR: ['ar.json'],
  BR: ['pt-br.json'],
  CR: ['hr.json'],
  CZ: ['cs.json'],
  DK: ['da.json'],
  FI: ['fi.json'],
  FR: ['fr.json'],
  GK: ['el.json'],
  GR: ['de.json'],
  HE: ['he.json'],
  HU: ['hu.json'],
  IT: ['it.json'],
  JP: ['ja.json'],
  KR: ['ko.json'],
  NL: ['nl.json'],
  NO: ['nb.json'],
  PL: ['pl.json'],
  PO: ['pt.json'],
  RO: ['ro.json'],
  RU: ['ru.json'],
  SC: ['zh-hans.json'],
  SH: ['sr-latn.json', 'sr.json'],
  SK: ['sk.json'],
  SL: ['sl.json'],
  SP: ['es.json'],
  SV: ['sv.json'],
  TC: ['zh-hant.json'],
  TU: ['tr.json'],
  UA: ['uk.json'],
  // ID?...
  ID: ['id.json'],
};
