export const tranList = [
  ['AR.json', 'ar.json'],
  ['BR.json', 'pt-br.json'],
  ['CR.json', 'hr.json'],
  ['CZ.json', 'cs.json'],
  ['DK.json', 'da.json'],
  ['FI.json', 'fi.json'],
  ['FR.json', 'fr.json'],
  ['GK.json', 'el.json'],
  ['GR.json', 'de.json'],
  ['HE.json', 'he.json'],
  ['HU.json', 'hu.json'],
  ['IT.json', 'it.json'],
  ['JP.json', 'ja.json'],
  ['KR.json', 'ko.json'],
  ['NL.json', 'nl.json'],
  ['NO.json', 'nb.json'],
  ['PL.json', 'pl.json'],
  ['PO.json', 'pt.json'],
  ['RO.json', 'ro.json'],
  ['RU.json', 'ru.json'],
  ['SC.json', 'zh-hans.json'],
  ['SH.json', 'sr-latn.json', 'sr.json'],
  ['SK.json', 'sk.json'],
  ['SL.json', 'sl.json'],
  ['SP.json', 'es.json'],
  ['SV.json', 'sv.json'],
  ['TC.json', 'zh-hant.json'],
  ['TU.json', 'tr.json'],
  ['UA.json', 'uk.json'],
  ['ID.json', 'id.json'],
].map((item) => Array.from(new Set(item.map((i) => i.toLowerCase()))));
