export const countries = [
  { country: "United States", zh: "美国", code: "US" },
  { country: "Angola", zh: "安哥拉", code: "AO" },
  { country: "Afghanistan", zh: "阿富汗", code: "AF" },
  { country: "Albania", zh: "阿尔巴尼亚", code: "AL" },
  { country: "Algeria", zh: "阿尔及利亚", code: "DZ" },
  { country: "Andorra", zh: "安道尔共和国", code: "AD" },
  { country: "Anguilla", zh: "安圭拉岛", code: "AI" },
  { country: "Antigua and Barbuda", zh: "安提瓜和巴布达", code: "AG" },
  { country: "Argentina", zh: "阿根廷", code: "AR" },
  { country: "Armenia", zh: "亚美尼亚", code: "AM" },
  { country: "Australia", zh: "澳大利亚", code: "AU" },
  { country: "Austria", zh: "奥地利", code: "AT" },
  { country: "Azerbaijan", zh: "阿塞拜疆", code: "AZ" },
  { country: "Bahamas", zh: "巴哈马", code: "BS" },
  { country: "Bahrain", zh: "巴林", code: "BH" },
  { country: "Bangladesh", zh: "孟加拉国", code: "BD" },
  { country: "Barbados", zh: "巴巴多斯", code: "BB" },
  { country: "Belarus", zh: "白俄罗斯", code: "BY" },
  { country: "Belgium", zh: "比利时", code: "BE" },
  { country: "Belize", zh: "伯利兹", code: "BZ" },
  { country: "Benin", zh: "贝宁", code: "BJ" },
  { country: "Bermuda Is.", zh: "百慕大群岛", code: "BM" },
  { country: "Bolivia", zh: "玻利维亚", code: "BO" },
  { country: "Botswana", zh: "博茨瓦纳", code: "BW" },
  { country: "Brazil", zh: "巴西", code: "BR" },
  { country: "Brunei", zh: "文莱", code: "BN" },
  { country: "Bulgaria", zh: "保加利亚", code: "BG" },
  { country: "Burkina-faso", zh: "布基纳法索", code: "BF" },
  { country: "Burma", zh: "缅甸", code: "MM" },
  { country: "Burundi", zh: "布隆迪", code: "BI" },
  { country: "Cameroon", zh: "喀麦隆", code: "CM" },
  { country: "Canada", zh: "加拿大", code: "CA" },
  { country: "Central African Republic", zh: "中非共和国", code: "CF" },
  { country: "Chad", zh: "乍得", code: "TD" },
  { country: "Chile", zh: "智利", code: "CL" },
  { country: "China", zh: "中国", code: "CN" },
  { country: "Colombia", zh: "哥伦比亚", code: "CO" },
  { country: "Congo", zh: "刚果", code: "CG" },
  { country: "Cook Is.", zh: "库克群岛", code: "CK" },
  { country: "Costa Rica", zh: "哥斯达黎加", code: "CR" },
  { country: "Cuba", zh: "古巴", code: "CU" },
  { country: "Cyprus", zh: "塞浦路斯", code: "CY" },
  { country: "Czech Republic", zh: "捷克", code: "CZ" },
  { country: "Denmark", zh: "丹麦", code: "DK" },
  { country: "Djibouti", zh: "吉布提", code: "DJ" },
  { country: "Dominica Rep.", zh: "多米尼加共和国", code: "DO" },
  { country: "Ecuador", zh: "厄瓜多尔", code: "EC" },
  { country: "Egypt", zh: "埃及", code: "EG" },
  { country: "EI Salvador", zh: "萨尔瓦多", code: "SV" },
  { country: "Estonia", zh: "爱沙尼亚", code: "EE" },
  { country: "Ethiopia", zh: "埃塞俄比亚", code: "ET" },
  { country: "Finland", zh: "芬兰", code: "FI" },
  { country: "Fiji", zh: "斐济", code: "FJ" },
  { country: "France", zh: "法国", code: "FR" },
  { country: "French Guiana", zh: "法属圭亚那", code: "GF" },
  { country: "French Polynesia", zh: "法属玻利尼西亚", code: "PF" },
  { country: "Germany", zh: "德国", code: "DE" },
  { country: "Gabon", zh: "加蓬", code: "GA" },
  { country: "Gambia", zh: "冈比亚", code: "GM" },
  { country: "Georgia", zh: "格鲁吉亚", code: "GE" },
  { country: "Ghana", zh: "加纳", code: "GH" },
  { country: "Gibraltar", zh: "直布罗陀", code: "GI" },
  { country: "Greece", zh: "希腊", code: "GR" },
  { country: "Grenada", zh: "格林纳达", code: "GD" },
  { country: "Guam", zh: "关岛", code: "GU" },
  { country: "Guatemala", zh: "危地马拉", code: "GT" },
  { country: "Guinea", zh: "几内亚", code: "GN" },
  { country: "Guyana", zh: "圭亚那", code: "GY" },
  { country: "Haiti", zh: "海地", code: "HT" },
  { country: "Honduras", zh: "洪都拉斯", code: "HN" },
  { country: "Hongkong", zh: "香港", code: "HK" },
  { country: "Hungary", zh: "匈牙利", code: "HU" },
  { country: "India", zh: "印度", code: "IN" },
  { country: "Iceland", zh: "冰岛", code: "IS" },
  { country: "Indonesia", zh: "印度尼西亚", code: "ID" },
  { country: "Iran", zh: "伊朗", code: "IR" },
  { country: "Iraq", zh: "伊拉克", code: "IQ" },
  { country: "Ireland", zh: "爱尔兰", code: "IE" },
  { country: "Israel", zh: "以色列", code: "IL" },
  { country: "Italy", zh: "意大利", code: "IT" },
  { country: "Japan", zh: "日本", code: "JP" },
  { country: "Jamaica", zh: "牙买加", code: "JM" },
  { country: "Jordan", zh: "约旦", code: "JO" },
  { country: "Kampuchea (Cambodia )", zh: "柬埔寨", code: "KH" },
  { country: "Kazakstan", zh: "哈萨克斯坦", code: "KZ" },
  { country: "Kenya", zh: "肯尼亚", code: "KE" },
  { country: "Korea", zh: "韩国", code: "KR" },
  { country: "Kuwait", zh: "科威特", code: "KW" },
  { country: "Kyrgyzstan", zh: "吉尔吉斯坦", code: "KG" },
  { country: "Laos", zh: "老挝", code: "LA" },
  { country: "Latvia", zh: "拉脱维亚", code: "LV" },
  { country: "Lebanon", zh: "黎巴嫩", code: "LB" },
  { country: "Lesotho", zh: "莱索托", code: "LS" },
  { country: "Liberia", zh: "利比里亚", code: "LR" },
  { country: "Libya", zh: "利比亚", code: "LY" },
  { country: "Liechtenstein", zh: "列支敦士登", code: "LI" },
  { country: "Lithuania", zh: "立陶宛", code: "LT" },
  { country: "Luxembourg", zh: "卢森堡", code: "LU" },
  { country: "Malaysia", zh: "马来西亚", code: "MY" },
  { country: "Macao", zh: "澳门", code: "MO" },
  { country: "Madagascar", zh: "马达加斯加", code: "MG" },
  { country: "Malawi", zh: "马拉维", code: "MW" },
  { country: "Maldives", zh: "马尔代夫", code: "MV" },
  { country: "Mali", zh: "马里", code: "ML" },
  { country: "Malta", zh: "马耳他", code: "MT" },
  { country: "Mauritius", zh: "毛里求斯", code: "MU" },
  { country: "Mexico", zh: "墨西哥", code: "MX" },
  { country: "Moldova, Republic of", zh: "摩尔多瓦", code: "MD" },
  { country: "Monaco", zh: "摩纳哥", code: "MC" },
  { country: "Mongolia", zh: "蒙古", code: "MN" },
  { country: "Montserrat Is", zh: "蒙特塞拉特岛", code: "MS" },
  { country: "Morocco", zh: "摩洛哥", code: "MA" },
  { country: "Mozambique", zh: "莫桑比克", code: "MZ" },
  { country: "Norway", zh: "挪威", code: "NO" },
  { country: "Namibia", zh: "纳米比亚", code: "NA" },
  { country: "Nauru", zh: "瑙鲁", code: "NR" },
  { country: "Nepal", zh: "尼泊尔", code: "NP" },
  { country: "Netherlands", zh: "荷兰", code: "NL" },
  { country: "New Zealand", zh: "新西兰", code: "NZ" },
  { country: "Nicaragua", zh: "尼加拉瓜", code: "NI" },
  { country: "Niger", zh: "尼日尔", code: "NE" },
  { country: "Nigeria", zh: "尼日利亚", code: "NG" },
  { country: "North Korea", zh: "朝鲜", code: "KP" },
  { country: "Oman", zh: "阿曼", code: "OM" },
  { country: "Pakistan", zh: "巴基斯坦", code: "PK" },
  { country: "Panama", zh: "巴拿马", code: "PA" },
  { country: "Papua New Cuinea", zh: "巴布亚新几内亚", code: "PG" },
  { country: "Paraguay", zh: "巴拉圭", code: "PY" },
  { country: "Peru", zh: "秘鲁", code: "PE" },
  { country: "Philippines", zh: "菲律宾", code: "PH" },
  { country: "Poland", zh: "波兰", code: "PL" },
  { country: "Portugal", zh: "葡萄牙", code: "PT" },
  { country: "Puerto Rico", zh: "波多黎各", code: "PR" },
  { country: "Qatar", zh: "卡塔尔", code: "QA" },
  { country: "Romania", zh: "罗马尼亚", code: "RO" },
  { country: "Russia", zh: "俄罗斯", code: "RU" },
  { country: "Singapore", zh: "新加坡", code: "SG" },
  { country: "Saint Lueia", zh: "圣卢西亚", code: "LC" },
  { country: "Saint Vincent", zh: "圣文森特岛", code: "VC" },
  { country: "San Marino", zh: "圣马力诺", code: "SM" },
  { country: "Sao Tome and Principe", zh: "圣多美和普林西比", code: "ST" },
  { country: "Saudi Arabia", zh: "沙特阿拉伯", code: "SA" },
  { country: "Senegal", zh: "塞内加尔", code: "SN" },
  { country: "Seychelles", zh: "塞舌尔", code: "SC" },
  { country: "Sierra Leone", zh: "塞拉利昂", code: "SL" },
  { country: "Slovakia", zh: "斯洛伐克", code: "SK" },
  { country: "Slovenia", zh: "斯洛文尼亚", code: "SI" },
  { country: "Solomon Is", zh: "所罗门群岛", code: "SB" },
  { country: "Somali", zh: "索马里", code: "SO" },
  { country: "South Africa", zh: "南非", code: "ZA" },
  { country: "Spain", zh: "西班牙", code: "ES" },
  { country: "Sri Lanka", zh: "斯里兰卡", code: "LK" },
  { country: "St.Lucia", zh: "圣卢西亚", code: "LC" },
  { country: "St.Vincent", zh: "圣文森特", code: "VC" },
  { country: "Sudan", zh: "苏丹", code: "SD" },
  { country: "Suriname", zh: "苏里南", code: "SR" },
  { country: "Swaziland", zh: "斯威士兰", code: "SZ" },
  { country: "Sweden", zh: "瑞典", code: "SE" },
  { country: "Switzerland", zh: "瑞士", code: "CH" },
  { country: "Syria", zh: "叙利亚", code: "SY" },
  { country: "Taiwan", zh: "台湾省", code: "TW" },
  { country: "Tajikstan", zh: "塔吉克斯坦", code: "TJ" },
  { country: "Tanzania", zh: "坦桑尼亚", code: "TZ" },
  { country: "Thailand", zh: "泰国", code: "TH" },
  { country: "Togo", zh: "多哥", code: "TG" },
  { country: "Tonga", zh: "汤加", code: "TO" },
  { country: "Trinidad and Tobago", zh: "特立尼达和多巴哥", code: "TT" },
  { country: "Tunisia", zh: "突尼斯", code: "TN" },
  { country: "Turkey", zh: "土耳其", code: "TR" },
  { country: "Turkmenistan", zh: "土库曼斯坦", code: "TM" },
  { country: "Uganda", zh: "乌干达", code: "UG" },
  { country: "Ukraine", zh: "乌克兰", code: "UA" },
  { country: "United Arab Emirates", zh: "阿拉伯联合酋长国", code: "AE" },
  { country: "United Kiongdom", zh: "英国", code: "GB" },
  { country: "Uruguay", zh: "乌拉圭", code: "UY" },
  { country: "Uzbekistan", zh: "乌兹别克斯坦", code: "UZ" },
  { country: "Venezuela", zh: "委内瑞拉", code: "VE" },
  { country: "Vietnam", zh: "越南", code: "VN" },
  { country: "Yemen", zh: "也门", code: "YE" },
  { country: "Yugoslavia", zh: "南斯拉夫", code: "YU" },
  { country: "Zimbabwe", zh: "津巴布韦", code: "ZW" },
  { country: "Zaire", zh: "扎伊尔", code: "ZR" },
  { country: "Zambia", zh: "赞比亚", code: "ZM" },
];
